### ISSUE TITLE
Crash when selecting Wi Fi Network 

### ISSUE THREAD

**Issue by leolost2605** [elementary/wingpanel-indicator-network#315]
### What Happened?

When selecting a wi fi network sometimes wingpanel crashes. Doesn't work 100% of the time but I think most of the times on an initial connect.

### Steps to Reproduce

1. Select a Wi fi network to connect to
2. With a bit of luck it will crash

### Expected Behavior

Don't crash

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ab371c4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ab371c288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ab372b1ef5b in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ab372b87a97 in g_assertion_message_expr () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ab3640c4396 in ??? () at /lib/x86_64-linux-gnu/libnma.so.0
#8  0x00007ab3640c8dbd in ??? () at /lib/x86_64-linux-gnu/libnma.so.0
#9  0x00007ab3640c9423 in ??? () at /lib/x86_64-linux-gnu/libnma.so.0
#10 0x00007ab3640c9513 in nma_wifi_dialog_new () at /lib/x86_64-linux-gnu/libnma.so.0
#11 0x00007ab3650977d9 in ??? () at /usr/lib/x86_64-linux-gnu/wingpanel/libnetwork.so
#12 0x00007ab3728dfcf7 in g_cclosure_marshal_VOID__OBJECTv ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ab3729016bd in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ab3729017c1 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ab372901883 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ab3729016bd in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ab372901a98 in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ab3650951f3 in ??? () at /usr/lib/x86_64-linux-gnu/wingpanel/libnetwork.so
#19 0x00007ab37209d0a4 in ??? () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ab3728e12fa in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ab37291090c in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ab372900ef2 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ab3729017c1 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ab372901883 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ab372366b74 in ??? () at /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#26 0x00007ab372203310 in ??? () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ab372203eaa in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ab371f3f407 in ??? () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#29 0x00007ab371f784ce in ??? () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#30 0x00007ab372b5c5b5 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ab372bbb717 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ab372b5ba53 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ab372a1688d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#34 0x000062cb41356a74 in wingpanel_application_main (args=0x7ffe316d4898, args_length1=1)
    at ../src/Application.vala:184
#35 0x000062cb41356ac1 in main (argc=1, argv=0x7ffe316d4898) at ../src/Application.vala:183
```

**Comment by spotlesscoder** [comment]
Does this happen on all WiFis? I've seen similar behaviour primarily on non-password protected networks
